version: '3.3'

services:
  db:
    image: postgres:${TAG:-alpine}
    command: >
      -c ssl=on
      -c ssl_ca_file='/var/lib/postgresql/ssl/ca.cert'
      -c ssl_cert_file=/var/lib/postgresql/ssl/server.cert
      -c ssl_key_file=/var/lib/postgresql/ssl/server.key
    restart: always
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DATABASE:-mikudb}'
      - 'POSTGRES_USER=${POSTGRES_USER:-miku}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-hatsune}'
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./data/ssl/ca.cert:/var/lib/postgresql/ssl/ca.cert
      - ./data/ssl/server.cert:/var/lib/postgresql/ssl/server.cert
      - ./data/ssl/server.key:/var/lib/postgresql/ssl/server.key

